exclude: "^(bruno/)"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: "^aws-backend/template\\.yaml$"
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.2
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: ["--fix", "--show-fixes"]
      # Run the formatter.
      - id: ruff-format
