[pytest]
addopts = -r a --cov=src --cov-report=term-missing
testpaths = tests
python_files = test_*.py
pythonpath = src
filterwarnings =
    ignore::DeprecationWarning
env =
    SECRET_KEY=SuperSecretKeyForTesting@!$%^&*123123
    DATABASE_URL=postgresql+asyncpg://postgres:$Test123@localhost:5432/$TestDB
